const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Car,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Car.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Bala: 0},
	{mapa: 0},
	{Coche: 0},
	{DesplazarHasta: 0},
	{RestringidoALaEscena: 0},
	{"8Direcciones": 0},
	{avion_01: 0},
	{Teclado: 0},
	{Departamento: 0},
	{marcaDepto: 0},
	{ArrayDeptos: 0},
	{instruccion: 0},
	{Temporizador: 0},
	{cuenta: 0},
	{retroa: 0},
	{Audio: 0},
	{doblaje_puntos: 0},
	{tipo_pregunta: 0},
	{btn_viaje: 0},
	{borde_invisible: 0},
	{velocidadMapa: 0},
	{aceleracionMapa: 0},
	{deptos: 0},
	{deptos2: 0},
	{limite_superior: 0},
	{limite_infeior: 0},
	{limite_izquierdo: 0},
	{limite_derecho: 0},
	{Depto_seleccionado: 0},
	{tiempoTotalCuenta: 0},
	{cuentaActual: 0},
	{sonando_volare: 0},
	{posicion_voyage: 0},
	{ya_volare: 0},
	{lista_tipo_actividad: 0},
	{actividad_seleccionada: 0},
	{contador_actividad: 0},
	{contacto_Depto: 0},
	{x_ini_avion: 0},
	{y_ini_avion2: 0},
	{yaSonoVoyage: 0},
	{i: 0}
];

self.InstanceType = {
	mapa: class extends self.ISpriteInstance {},
	avion_01: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	marcaDepto: class extends self.ISpriteInstance {},
	ArrayDeptos: class extends self.IArrayInstance {},
	instruccion: class extends self.ITextInstance {},
	cuenta: class extends self.ITextInstance {},
	retroa: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	doblaje_puntos: class extends self.ITextInstance {},
	tipo_pregunta: class extends self.ITextInstance {},
	btn_viaje: class extends self.IButtonInstance {},
	borde_invisible: class extends self.ITiledBackgroundInstance {}
}